### PR TITLE
Use description meta tag as description if og:description is missing

### PR DESCRIPTION
**Pull request by nikk-dzhurov**

### CODE REVIEW

**Comment by otiai10** [comment]
@nikk-dzhurov thank you very much for the request.

At my first glance, it's better to expand the conditions inside the existing `IsDescription` method, rather than create another method. `IsDescription` should represent if the tag **can be** a description.

What do you think? Thank you in advance.

**Comment by nikk-dzhurov** [comment]
Hi @otiai10 :)

My point is that `og:description` should be with higher priority. If we have 2 sources for that description property we probably should choose `og:description` one. I don't know how to twist the logic so i can achive that in one check func().

Do you have any ideas ?    

Also I have other suggestions:
- JSON representations for structures should be camelCased
- URL property should be string as other nested URL/SURL properties

Thanks for the reply :)

**Comment by otiai10** [comment]
> My point is that og:description should be with higher priority.

Ah... I've got it. Right, it should have any priority. I'll tackle this after merging your request.

> JSON representations for structures should be camelCased

Isn't it?

> URL property should be string as other nested URL/SURL properties

I have an idea. Wait a bit and stay tuned.

**Comment by nikk-dzhurov** [comment]
Thanks for merging my PR.

About JSON representations. You can check out this example: https://play.golang.org/p/Avw2bmUTakU
It's just shortened version of full go example: https://gobyexample.com/json.
So if we do not pass tag for property in the structure, `json.Marshall()` will use it's name. In that particular case all properties starts with uppercase letter.

Also it would be nice to `omitempty` properties that are not required. For an example if we want to store large number of JSON objects(for cache or other purposes), that will save some memory/traffic. :)

**Comment by otiai10** [comment]
I guess what you're talking about is [UCC and LCC](https://en.wikipedia.org/wiki/Camel_case), `json.Marshal` (misspelled `Marshall`) originally use UCC[[1]](https://play.golang.org/p/-k07lYm7dbk).

IMO, so far, because there is no specific reason to use LCC purposely.

For `omitempty`, I would appreciate if you create another issue/pull-request.

**Comment by otiai10** [comment]
> URL property should be string as other nested URL/SURL properties

I checked my application's code, which is the biggest motivation of this OpenGraph package, and found the URL informations are necessary. It's better to let Go parse URL in server side than do it with [JavaScript URL API](https://caniuse.com/#search=URL).

I prefer keep it as an object.

**Comment by otiai10** [comment]
Please create another issue/pull-request for further discussion to make it clear.

**Pull request merged**
